#!/bin/bash
blanco='\033[38;5;231m'
amarillo='\033[38;5;228m'
azul='\033[38;5;14m'
morado='\033[38;5;147m'
moradoL='\033[38;5;54m'
rojo='\033[0;31m'
verde='\033[38;5;148m'
verdeR='\033[38;5;40m'
yellow='\033[0;33m'
rosa='\033[38;5;213m'
melon='\033[38;5;208m'
guinda='\033[38;5;161m'
azulR="\033[38;5;18m"
cierre='\033[0m'
bar1="\e[1;30m◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘◘\e[0m"
bar2="\033[38;5;226m---------------------------------------------------------\033[0m"
bar3="\033[38;5;226m--------------------- = MENU = --------------------------\033[0m"
#PATH DE ARCHVOS
dir_token=/etc/token
file_token=$dir_token/BD
file_pass=$dir_token/.passw
file_client=$dir_token/.clientes
#DIRECTORIOS
mkdir_dir (){
  if [ -d $dir_token ]; then
	    echo
	    else
	     mkdir $dir_token
fi
if [ -f $file_token ]; then
	    echo
	    else
	     touch $file_token
       chmod 755 $file_token
fi
if [ -f $file_pass ]; then
	    echo
	    else
	     touch $file_passw
       chmod 755 $file_pass
fi
if [ -f $file_client ]; then
	    echo
	    else
	     touch $file_client
       chmod 755 $file_client
fi
}
#HORA DE MEXICO
echo "America/Mexico_City" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Mexico_City /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
#MENSAJE DE BINEVENIDA
msg () {
echo -e "$bar1"
    echo -e "${rojo}########################################################${cierre}"
    echo -e "${rojo}#    ${verde}Bienvenido${blanco}, Gracias por utilizar Onlycode ${verdeR}VPN     ${rojo}# ${cierre}"
    echo -e "${rojo}#    ${blanco}Este SCRIPT autoriza su token ID para usar${cierre}        ${rojo}# ${cierre}"
    echo -e "${rojo}#    ${blanco}Nuestra apk...                            ${cierre}        ${rojo}# ${cierre}"
    echo -e "${rojo}#   ${melon}-----------------------------------------------    ${rojo}#${cierre}"
    echo -e "${rojo}#          ${blanco}dev: ${moradoL}@dankelthaher ${blanco}- ${amarillo}Onlycode ${verdeR}VPN${cierre}           ${rojo}#${cierre}"
    echo -e "${rojo}########################################################${cierre}"
    echo -e "$bar1"
}
#DEFINE CONTRASEÑA UNICA
define (){
	mkdir_dir
echo -e "$bar1"
echo -e "${rojo}Antes de comenzar deve ingresar su contraseña"
echo -e "$bar2"
read -p "$(echo -e "${amarillo}[ingrese]: ${cierre}")" pass
echo -e "$pass" >> $file_pass
echo -e "$bar1"
}
#FUNCION DE CREACION DE USUARIOS
crear () {
    clear
    TITLE="${blanco}Onlycode ${verdeR}VPN"
echo -e "$TITLE"
echo -e ""
echo -e " AUTORIZAR TOKEN ID"
echo -e "$bar1"
echo -e ""
echo -e "${blanco}Ingrese el Nombre del Usuario${cierre}"
echo -e "$bar2"
read -p $'\e[32m  [ingrese]: \e[0m' usr
echo -e "$bar1"
echo -e "${blanco}Ingrese el Token que desea Autorizar${cierre}"
echo -e "$bar2"
read -p $'\e[32m  [Token ID]: \e[0m' token

# Check If Username Exist, Else Proceed
egrep "^$token" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
clear
echo -e "$bar1"
echo -e "$TITLE"
echo ""
echo -e "\e[31m El Token ya existe en su servidor, intente con otro Token\e[0m."
exit 0
else
echo -e "$bar2"
read -p $'\e[32m  Dias activos: \e[0m' Days
echo -e "$bar1"
clear
sleep 1
IPADDR=$(wget -4qO- http://ipinfo.io/ip)
Today=`date +%s`
Days_Detailed=$(( $Days * 86400 ))
Expire_On=$(($Today + $Days_Detailed))
Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g' )"
dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
stunnel4port="$(netstat -nlpt | grep -i stunnel4 | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
openvpnport="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
pyport="$(netstat -nlpt | grep -i python | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
squidport="$(cat /etc/squid/squid.conf | grep -i http_port | awk '{print $2}' | xargs | sed -e 's/ /, /g')"
useradd -m -s /bin/false -e $Expiration $token > /dev/null
egrep "^$token" /etc/passwd &> /dev/null
DIA=`date +"%d/%m/%Y"`
HORA=`date +"%H:%M"`
echo -e "$(cat $file_pass)\n$(cat $file_pass)\n" | passwd $token &> /dev/null
echo -e "$token" >> $file_token
echo -e "$usr  $token  $DIA     $HORA"  >> $file_client
clear
echo -e "$bar1"
echo -e "$TITLE"
echo -e "$bar2"
echo ""
echo -e " Datos del Usuario:"
echo -e "\e[32m  Token ID: \e[0m"$token
echo -e "\e[32m  Caducidad de la cuenta: \e[0m"$Expiration_Display
echo -e ""
echo -e "$bar1"
echo -e "\e[32m  Host/IP: \e[0m"$IPADDR
echo -e "\e[32m  Perto OpenSSH: \e[0m"$opensshport
echo -e "\e[32m  Puerto Dropbear: \e[0m"$dropbearport
echo -e "\e[32m  Puerto SSL: \e[0m"$stunnel4port
echo -e "\e[32m  Puertos Squid: \e[0m"$squidport
echo -e "\e[32m  Puertos Openvpn: \e[0m"$openvpnport
echo -e "\e[32m  Puertos python: \e[0m"$openvpnport
echo -e "$bar1"
fi
}

#ELIMINAR ID
eliminar () {
  unset token
  echo -e "$TITLE"
echo -e ""
    i=1
	for total in `cat $file_token`; do
	[[ -f "$total" ]] && continue
	option_id[$i]="$total"
    echo -e "$bar1"
	echo -e "${azul} [$i] > $blanco$total"
	let i++
    done
	i=$(($i - 1))
    echo -e "$bar1"
	while [[ -z ${option_id[$slct_option]} ]]; do
read -p "seleccione [1-$i]: " slct_option
tput cuu1 && tput dl1
done
token="${option_id[$slct_option]}"
sleep 2
egrep "^$token" /etc/passwd &> /dev/null
if [ $? -eq 0 ]; then
  userdel -f $token
  rm -rf /home/$token
  sed -i "s;$token;;g" $file_token
  sed -i '/^$/d' $file_token
  sed -i "/$token/d" $file_client
  sed -i '/^$/d' $file_client
	clear
	echo -e ""
  echo -e "$TITLE"
  echo -e "$bar1"
	echo -e " Token Eliminado con Exito"
	echo -e "$bar1"
else
	clear
	echo -e ""
  echo -e "$TITLE"
  echo -e "$bar1"
	echo -e " El Token que ingresaste no existe"
	echo -e "$bar1"
fi
}

#EDITAR TOKEN
editar (){
unset token
  echo -e "$TITLE"
echo -e ""
    i=1
	for total in `cat $file_token`; do
	[[ -f "$total" ]] && continue
	option_id[$i]="$total"
    echo -e "$bar1"
	echo -e "${azul} [$i] > $blanco$total"
	let i++
    done
	i=$(($i - 1))
    echo -e "$bar1"
	while [[ -z ${option_id[$slct_option]} ]]; do
read -p "seleccione [1-$i]: " slct_option
tput cuu1 && tput dl1
done
token="${option_id[$slct_option]}"
sleep 2
egrep "^$token" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
echo -e "${blanco}Ingrese el numero de dias${cierre}"
echo -e "$bar2"
read -p " [Días]: " Days
Today=`date +%s`
Days_Detailed=$(( $Days * 86400 ))
Expire_On=$(($Today + $Days_Detailed))
Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
passwd -u $token
usermod -e $Expiration $token
egrep "^$token" /etc/passwd >/dev/null
echo -e "$PASSWDT\n$PASSWDT\n"|passwd $token &> /dev/null
clear
echo -e "$TILTE"
echo -e "$bar1"
echo -e ""
echo -e " token ID: $token"
echo -e "$bar2"
echo -e " Caducidad de cuenta modificada: $Days Dias"
echo -e "$bar2"
echo -e " La cuenta vence el: $Expiration_Display"
echo -e "$bar1"
else
clear
echo -e "$TILTE"
echo -e "$bar1"
echo -e ""
echo -e " El Token que ingresaste no existe"
echo -e ""
fi
}
#MOSTAR USURIOS
lista (){
	if [ -f /etc/debian_version ]; then
	UIDN=1000
elif [ -f /etc/redhat-release ]; then
	UIDN=500
elif [ -f /etc/ubuntu_version ]; then
	UIDN=500
else
	UIDN=500
fi
clear
echo -e "$TILTE"
echo -e "$bar1"
echo -e ""
echo -e " Token ID               Expiracion"
echo -e "$bar1"
while read Checklist
do
        Spacer=""
        Account="$(echo $Checklist | cut -d: -f1)"
        ID="$(echo $Checklist | grep -v nobody | cut -d: -f3)"
        Exp="$(chage -l $Account | grep "Account expires" | awk -F": " '{print $2}')"
        if [[ $ID -ge $UIDN ]]; then
        echo -e " $Account   " "   $Exp"
        fi
done < /etc/passwd
No_Users="$(awk -F: '$3 >= '$UIDN' && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo -e "$bar2"
echo -e " Numero de Tokens: "$No_Users
echo -e "$bar2"
}
#ELIMINAR EXPIRADOS
expirados () {
clear
unset token
echo -e ""
echo -e "$TITLE"
echo -e "$bar1"

datenow=$(date +%s)
for token in $(awk -F: '{print $1}' /etc/passwd); do
expdate=$(chage -l $token|awk -F: '/Account expires/{print $2}')
echo $expdate | grep -q never && continue
echo -n "Token \`$token' expira el $expdate ... "
expsec=$(date +%s --date="$expdate")
diff=$(echo $datenow - $expsec|bc -l)
echo $diff | grep -q ^\- && echo okay && continue
userdel -r -f $token  &> /dev/null
done
echo -e ""
echo -e "  Todos \e[31mLos token expirados\e[0m han sido Eliminados"
echo -e "$bar1"
}
informacion_clientes () {
  GreenBG="\033[42;31m"
     echo -e "${GreenBG}                 INFORMACION DE CLIENTES                 ${cierre}"
    echo -e "$bar2"
    cat $file_client | column -t
    echo -e "$bar1"

}
online (){                                                               
clear
TITLE="${blanco}Onlycode ${verdeR}VPN"

if [ -e "/var/log/auth.log" ]; then
        LOG="/var/log/auth.log";
fi
if [ -e "/var/log/secure" ]; then
        LOG="/var/log/secure";
fi
                
data=( `ps aux | grep -i dropbear | awk '{print $2}'`)
GreenBG="\033[42;31m"
     echo -e "${GreenBG}        Usuarios ONLINE Dropbear                ${cierre}"
    echo -e "$bar2"
    echo ""
cat $LOG | grep -i dropbear | grep -i "Password auth succeeded" > /tmp/login-db.txt
for PID in "${data[@]}"
do
        cat /tmp/login-db.txt | grep "dropbear\[$PID\]" > /tmp/login-db-pid.txt
        NUM=`cat /tmp/login-db-pid.txt | wc -l`
        USER=`cat /tmp/login-db-pid.txt | awk '{print $10}'`
        IP=`cat /tmp/login-db-pid.txt | awk '{print $12}'`
        if [ $NUM -eq 1 ]; then
                echo -e "Token: $USER - ${verdeR}[ON]${cierre} -"
                fi
done
GreenBG="\033[42;31m"
echo ""
     echo -e "${GreenBG}         Usuarios ONLINE OpenSSH                ${cierre}"
    echo -e "$bar2"
    echo ""
cat $LOG | grep -i sshd | grep -i "Accepted password for" > /tmp/logins-db.txt
data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);

for PID in "${data[@]}"
do
        cat /tmp/logins-db.txt | grep "sshd\[$PID\]" > /tmp/login-db-pid.txt;
        NUM=`cat /tmp/login-db-pid.txt | wc -l`;
        USER=`cat /tmp/login-db-pid.txt | awk '{print $9}'`;
        IP=`cat /tmp/login-db-pid.txt | awk '{print $11}'`;
        if [ $NUM -eq 1 ]; then
                echo -e "Token: $USER - ${verdeR}[ON]${cierre} -";
        fi
done
if [ -f "/etc/openvpn/openvpn-status.log" ]; then
        line=`cat /etc/openvpn/openvpn-status.log | wc -l`
        a=$((3+((line-8)/2)))
        b=$(((line-8)/2))
        echo ""
        echo -e "${GreenBG}          Usuarios ONLINE Openvpn               ${cierre}"
    echo -e "$bar2"
    echo ""
        
        cat /etc/openvpn/openvpn-status.log | head -n $a | tail -n $b | cut -d "," -f 1,2,5 | sed -e 's/,/   /g' > /tmp/vpn-login-db.txt
        cat /tmp/vpn-login-db.txt
fi

echo " "
echo " "
}
No_token="$(cat /etc/token/BD | wc -l)"

# ==============================================
# PANEL ULTRA AVANZADO - INSTALACIÓN DESDE ZIP
# ==============================================

instalar_panel_nextjs() {
    clear
    echo -e "$bar1"
    echo -e "${verde}     🚀 PANEL ULTRA AVANZADO - ONLYCODE VPN PRO${cierre}"
    echo -e "$bar1"
    
    # Verificar root
    if [ "$EUID" -ne 0 ]; then 
        echo -e "${rojo}❌ Ejecutar como root${cierre}"
        return 1
    fi
    
    # Solicitar configuración
    echo -e "${amarillo}⚙️  Configuración del Panel${cierre}"
    echo -e "$bar2"
    read -p "Usuario admin [admin]: " ADMIN_USER
    ADMIN_USER=${ADMIN_USER:-admin}
    read -s -p "Contraseña admin [admin123]: " ADMIN_PASS
    echo
    ADMIN_PASS=${ADMIN_PASS:-admin123}
    read -p "Puerto del panel [3000]: " PANEL_PORT
    PANEL_PORT=${PANEL_PORT:-3000}
    read -p "Puerto API [8080]: " API_PORT
    API_PORT=${API_PORT:-8080}
    
    echo -e "\n${amarillo}📦 Instalando dependencias necesarias...${cierre}"
    
    # Instalar Node.js 18+
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - >/dev/null 2>&1
    apt-get install -y nodejs >/dev/null 2>&1
    
    # Instalar PM2 globalmente
    npm install -g pm2 >/dev/null 2>&1
    
    # Instalar PHP y dependencias
    apt-get install -y php php-cli php-curl php-json php-sqlite3 php-zip unzip wget curl git >/dev/null 2>&1
    
    echo -e "${verde}✅ Dependencias instaladas${cierre}"
    
    # Crear directorios
    PANEL_DIR="/var/www/onlycode-panel"
    API_DIR="/var/www/onlycode-api"
    BACKUP_DIR="/root/panel-backup"
    
    # Limpiar directorios anteriores si existen
    if [ -d "$PANEL_DIR" ]; then
        echo -e "${amarillo}📦 Creando backup del panel anterior...${cierre}"
        mkdir -p $BACKUP_DIR
        mv $PANEL_DIR $BACKUP_DIR/panel-backup-$(date +%Y%m%d-%H%M%S)
    fi
    
    mkdir -p $PANEL_DIR $API_DIR
    
    echo -e "${amarillo}📥 Descargando Panel Ultra Avanzado...${cierre}"
    
    # URL DEL ZIP - CAMBIA ESTA URL POR LA UBICACIÓN DE TU ZIP
    # Ejemplo: https://tu-dominio.com/panel-onlycode.zip
    # O usando Dropbox: https://www.dropbox.com/s/xxxxx/panel-onlycode.zip?dl=1
    ZIP_URL="https://raw.githubusercontent.com/RmXF/Dev/main/panel-onlycode.zip"
    
    # Intentar descargar el ZIP
    wget -O /tmp/panel-onlycode.zip "$ZIP_URL" 2>/dev/null
    
    if [ $? -ne 0 ] || [ ! -s /tmp/panel-onlycode.zip ]; then
        echo -e "${rojo}❌ No se pudo descargar el panel desde: $ZIP_URL${cierre}"
        echo -e "${amarillo}📌 Por favor, introduce la URL de tu ZIP:${cierre}"
        read -p "URL del ZIP: " CUSTOM_URL
        if [ -n "$CUSTOM_URL" ]; then
            wget -O /tmp/panel-onlycode.zip "$CUSTOM_URL" 2>/dev/null
        fi
        
        if [ ! -s /tmp/panel-onlycode.zip ]; then
            echo -e "${rojo}❌ No se pudo descargar el panel. Instalación cancelada${cierre}"
            return 1
        fi
    fi
    
    # Verificar que es un ZIP válido
    if ! file /tmp/panel-onlycode.zip | grep -q "Zip archive"; then
        echo -e "${rojo}❌ El archivo descargado no es un ZIP válido${cierre}"
        rm -f /tmp/panel-onlycode.zip
        return 1
    fi
    
    echo -e "${amarillo}📦 Descomprimiendo archivos del panel...${cierre}"
    
    # Descomprimir el panel
    unzip -o /tmp/panel-onlycode.zip -d $PANEL_DIR >/dev/null 2>&1
    
    if [ $? -ne 0 ]; then
        echo -e "${rojo}❌ Error al descomprimir el ZIP${cierre}"
        rm -f /tmp/panel-onlycode.zip
        return 1
    fi
    
    # Verificar si se descomprimió correctamente y tiene package.json
    if [ ! -f "$PANEL_DIR/package.json" ]; then
        # Buscar si el ZIP tenía una carpeta raíz
        SUBDIR=$(find $PANEL_DIR -maxdepth 2 -name "package.json" -type f | head -1 | xargs dirname 2>/dev/null)
        if [ -n "$SUBDIR" ] && [ "$SUBDIR" != "$PANEL_DIR" ]; then
            echo -e "${amarillo}📁 Moviendo archivos desde subdirectorio...${cierre}"
            mv $SUBDIR/* $PANEL_DIR/ 2>/dev/null
            mv $SUBDIR/.[!.]* $PANEL_DIR/ 2>/dev/null
            rmdir $SUBDIR 2>/dev/null
        else
            echo -e "${rojo}❌ El ZIP no contiene un panel válido (package.json no encontrado)${cierre}"
            rm -f /tmp/panel-onlycode.zip
            return 1
        fi
    fi
    
    rm -f /tmp/panel-onlycode.zip
    echo -e "${verde}✅ Panel descomprimido correctamente${cierre}"
    
    # Guardar credenciales del panel
    echo "$ADMIN_USER:$ADMIN_PASS" > /etc/onlycode-panel-auth
    chmod 600 /etc/onlycode-panel-auth
    
    # ==============================================
    # CREAR API PHP (Siempre se crea fresca)
    # ==============================================
    echo -e "${amarillo}🔧 Configurando API PHP...${cierre}"
    
    cat > $API_DIR/index.php << 'PHPAPI'
<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE');
header('Access-Control-Allow-Headers: Content-Type, Authorization');

define('TOKEN_FILE', '/etc/token/BD');
define('CLIENT_FILE', '/etc/token/.clientes');
define('LIMITS_FILE', '/etc/token/limits');

function authenticate() {
    $headers = getallheaders();
    if (!isset($headers['Authorization'])) {
        http_response_code(401);
        echo json_encode(['error' => 'No autorizado']);
        exit;
    }
    
    $auth = base64_decode(str_replace('Basic ', '', $headers['Authorization']));
    list($user, $pass) = explode(':', $auth);
    
    $panel_auth = file_get_contents('/etc/onlycode-panel-auth');
    $creds = explode(':', $panel_auth);
    
    if ($user !== trim($creds[0]) || $pass !== trim($creds[1])) {
        http_response_code(401);
        echo json_encode(['error' => 'Credenciales inválidas']);
        exit;
    }
    return true;
}

function getLimits() {
    $limits = [];
    if (file_exists(LIMITS_FILE)) {
        $lines = file(LIMITS_FILE, FILE_IGNORE_NEW_LINES);
        foreach ($lines as $line) {
            if (strpos($line, ':') !== false) {
                list($user, $limit) = explode(':', $line);
                $limits[$user] = (int)$limit;
            }
        }
    }
    return $limits;
}

function saveLimit($username, $limit) {
    $limits = getLimits();
    $limits[$username] = $limit;
    $content = '';
    foreach ($limits as $user => $lim) {
        $content .= "$user:$lim\n";
    }
    file_put_contents(LIMITS_FILE, $content);
}

function getActiveConnections($username) {
    $count = 0;
    $log = file_exists('/var/log/auth.log') ? '/var/log/auth.log' : '/var/log/secure';
    if (file_exists($log)) {
        $output = shell_exec("grep -c 'Accepted password for $username' $log 2>/dev/null");
        $count = (int)$output;
    }
    return $count;
}

function getUsers() {
    $users = [];
    $limits = getLimits();
    if (file_exists(TOKEN_FILE)) {
        $tokens = array_filter(file(TOKEN_FILE, FILE_IGNORE_NEW_LINES));
        foreach ($tokens as $token) {
            $token = trim($token);
            if (empty($token)) continue;
            
            $user_data = shell_exec("chage -l $token 2>/dev/null");
            if ($user_data) {
                preg_match('/Account expires.*: (.+)$/m', $user_data, $exp_match);
                $expires = trim($exp_match[1] ?? 'never');
                $active_cons = getActiveConnections($token);
                $max_cons = $limits[$token] ?? 1;
                
                $users[] = [
                    'username' => $token,
                    'expiration' => $expires,
                    'status' => ($expires === 'never' || strtotime($expires) > time()) ? 'active' : 'inactive',
                    'active_connections' => $active_cons,
                    'max_connections' => $max_cons,
                    'limit_reached' => $active_cons >= $max_cons
                ];
            }
        }
    }
    return $users;
}

function createUser($username, $password, $days, $max_connections) {
    $check = shell_exec("id $username 2>/dev/null");
    if ($check) return ['error' => 'Usuario ya existe'];
    
    $exp_date = date('Y-m-d', strtotime("+$days days"));
    $create = shell_exec("useradd -m -s /bin/false -e $exp_date $username 2>&1");
    if ($create) return ['error' => $create];
    
    shell_exec("echo '$username:$password' | chpasswd");
    file_put_contents(TOKEN_FILE, $username . "\n", FILE_APPEND);
    saveLimit($username, $max_connections);
    
    $date = date('d/m/Y');
    $time = date('H:i');
    file_put_contents(CLIENT_FILE, "$username $username $date $time\n", FILE_APPEND);
    
    return [
        'success' => true,
        'username' => $username,
        'password' => $password,
        'expiration' => $exp_date,
        'days' => $days,
        'max_connections' => $max_connections
    ];
}

function deleteUser($username) {
    shell_exec("userdel -r -f $username 2>&1");
    
    if (file_exists(TOKEN_FILE)) {
        $tokens = file(TOKEN_FILE, FILE_IGNORE_NEW_LINES);
        $tokens = array_filter($tokens, fn($t) => trim($t) !== $username);
        file_put_contents(TOKEN_FILE, implode("\n", $tokens) . "\n");
    }
    
    if (file_exists(LIMITS_FILE)) {
        $limits = getLimits();
        unset($limits[$username]);
        $content = '';
        foreach ($limits as $user => $lim) {
            $content .= "$user:$lim\n";
        }
        file_put_contents(LIMITS_FILE, $content);
    }
    
    if (file_exists(CLIENT_FILE)) {
        $clients = file(CLIENT_FILE, FILE_IGNORE_NEW_LINES);
        $clients = array_filter($clients, fn($c) => strpos($c, $username) !== 0);
        file_put_contents(CLIENT_FILE, implode("\n", $clients) . "\n");
    }
    
    return ['success' => true];
}

function extendUser($username, $days) {
    $current_exp = shell_exec("chage -l $username | grep 'Account expires' | cut -d: -f2");
    $current_exp = trim($current_exp);
    
    if ($current_exp === 'never' || empty($current_exp)) {
        $new_exp = date('Y-m-d', strtotime("+$days days"));
    } else {
        $current_timestamp = strtotime($current_exp);
        if ($current_timestamp < time()) {
            $new_timestamp = time() + ($days * 86400);
        } else {
            $new_timestamp = $current_timestamp + ($days * 86400);
        }
        $new_exp = date('Y-m-d', $new_timestamp);
    }
    
    shell_exec("usermod -e $new_exp $username");
    return ['success' => true, 'new_expiration' => $new_exp];
}

function updateLimit($username, $max_connections) {
    saveLimit($username, $max_connections);
    return ['success' => true, 'max_connections' => $max_connections];
}

function getStats() {
    $total_users = shell_exec("cat /etc/passwd | grep -c '/home'");
    $online_users = shell_exec("ps aux | grep -E 'sshd|dropbear' | grep -v grep | wc -l");
    $load = sys_getloadavg();
    
    $meminfo = file_get_contents('/proc/meminfo');
    preg_match('/MemTotal:\s+(\d+)/', $meminfo, $mem_total);
    preg_match('/MemAvailable:\s+(\d+)/', $meminfo, $mem_avail);
    $mem_used = $mem_total[1] - $mem_avail[1];
    
    return [
        'total_users' => (int)$total_users,
        'online_users' => (int)$online_users,
        'server_load' => round($load[0], 2),
        'cpu_usage' => round($load[0] * 10, 2),
        'disk_usage' => disk_free_space('/') ? round(100 - (disk_free_space('/') / disk_total_space('/') * 100), 2) : 0,
        'memory_total' => round($mem_total[1] / 1024 / 1024, 2),
        'memory_used' => round($mem_used / 1024 / 1024, 2),
        'memory_percent' => round(($mem_used / $mem_total[1]) * 100, 2)
    ];
}

$method = $_SERVER['REQUEST_METHOD'];
$path = $_SERVER['PATH_INFO'] ?? '/';

if ($path !== '/health') {
    authenticate();
}

switch ($path) {
    case '/users':
        if ($method === 'GET') {
            echo json_encode(getUsers());
        } elseif ($method === 'POST') {
            $data = json_decode(file_get_contents('php://input'), true);
            echo json_encode(createUser($data['username'], $data['password'], $data['days'], $data['max_connections'] ?? 1));
        }
        break;
    case '/stats':
        echo json_encode(getStats());
        break;
    case '/health':
        echo json_encode(['status' => 'ok', 'timestamp' => date('c')]);
        break;
    default:
        if (preg_match('/^\/users\/(.+)$/', $path, $matches)) {
            $username = $matches[1];
            if ($method === 'DELETE') {
                echo json_encode(deleteUser($username));
            } elseif ($method === 'PUT') {
                $data = json_decode(file_get_contents('php://input'), true);
                if (isset($data['days'])) {
                    echo json_encode(extendUser($username, $data['days']));
                } elseif (isset($data['max_connections'])) {
                    echo json_encode(updateLimit($username, $data['max_connections']));
                }
            }
        } else {
            http_response_code(404);
            echo json_encode(['error' => 'Endpoint no encontrado']);
        }
}
PHPAPI

    # ==============================================
    # INSTALAR DEPENDENCIAS Y EJECUTAR PANEL
    # ==============================================
    
    echo -e "${amarillo}📦 Instalando dependencias de Node.js...${cierre}"
    cd $PANEL_DIR
    npm install >/dev/null 2>&1
    
    if [ $? -ne 0 ]; then
        echo -e "${rojo}❌ Error al instalar dependencias${cierre}"
        return 1
    fi
    
    echo -e "${amarillo}🏗️  Construyendo el panel...${cierre}"
    npm run build >/dev/null 2>&1
    
    # ==============================================
    # CONFIGURAR SERVICIOS
    # ==============================================
    
    # Servicio API
    cat > /etc/systemd/system/onlycode-api.service << SERVICES
[Unit]
Description=Onlycode VPN API Service
After=network.target

[Service]
Type=simple
User=www-data
WorkingDirectory=$API_DIR
ExecStart=/usr/bin/php -S 0.0.0.0:$API_PORT $API_DIR/index.php
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
SERVICES

    # Iniciar Next.js con PM2
    cd $PANEL_DIR
    pm2 stop onlycode-panel >/dev/null 2>&1
    pm2 delete onlycode-panel >/dev/null 2>&1
    pm2 start npm --name "onlycode-panel" -- start
    pm2 save
    pm2 startup >/dev/null 2>&1
    
    # Iniciar servicios
    systemctl daemon-reload
    systemctl enable onlycode-api.service
    systemctl restart onlycode-api.service
    
    # ==============================================
    # CONFIGURAR FIREWALL
    # ==============================================
    
    if command -v ufw &> /dev/null; then
        ufw allow $PANEL_PORT/tcp >/dev/null 2>&1
        ufw allow $API_PORT/tcp >/dev/null 2>&1
    fi
    
    # ==============================================
    # MOSTRAR INFORMACIÓN FINAL
    # ==============================================
    
    IPADDR=$(wget -4qO- http://ipinfo.io/ip 2>/dev/null || echo "127.0.0.1")
    
    clear
    echo -e "$bar1"
    echo -e "${verde}✅ PANEL ULTRA AVANZADO INSTALADO CORRECTAMENTE${cierre}"
    echo -e "$bar1"
    echo -e "${blanco}📱 Panel Web:${cierre} ${amarillo}http://$IPADDR:$PANEL_PORT${cierre}"
    echo -e "${blanco}🔌 API Endpoint:${cierre} ${amarillo}http://$IPADDR:$API_PORT${cierre}"
    echo -e "${blanco}👤 Usuario Admin:${cierre} ${verde}$ADMIN_USER${cierre}"
    echo -e "${blanco}🔑 Contraseña:${cierre} ${verde}$ADMIN_PASS${cierre}"
    echo -e "$bar2"
    echo -e "${amarillo}📊 Características del Panel:${cierre}"
    echo -e "  ${verde}✓${blanco} Dashboard profesional con estadísticas en tiempo real"
    echo -e "  ${verde}✓${blanco} Límite de conexiones simultáneas por usuario"
    echo -e "  ${verde}✓${blanco} Gestión completa de usuarios (crear/eliminar/extender)"
    echo -e "  ${verde}✓${blanco} Monitoreo de usuarios conectados"
    echo -e "  ${verde}✓${blanco} Diseño moderno y responsive"
    echo -e "$bar2"
    echo -e "${amarillo}📊 Comandos útiles:${cierre}"
    echo -e "  ${blanco}• Ver logs del panel:${cierre} pm2 logs onlycode-panel"
    echo -e "  ${blanco}• Reiniciar panel:${cierre} pm2 restart onlycode-panel"
    echo -e "  ${blanco}• Ver API status:${cierre} systemctl status onlycode-api"
    echo -e "  ${blanco}• Reiniciar API:${cierre} systemctl restart onlycode-api"
    echo -e "  ${blanco}• Backup del panel:${cierre} cp -r $PANEL_DIR $BACKUP_DIR"
    echo -e "$bar1"
    
    read -p "Presione ENTER para continuar..."
}

#MENU DE USUARIOS
menu () {
  clear
echo -e "${melon}               == Token Auth == (${amarillo}onlycode${cierre}${melon})
${bar1}
${morado}TOTAL DE REGISTROS: ${rojo}>${cierre} ${azul}ID: ${blanco}$No_token  ${cierre}
${bar3}
${azul}[1]${cierre} ${rojo}>${cierre} ${blanco}Agregar ${verdeR}ID${cierre}
${azul}[2]${cierre} ${rojo}>${cierre} ${blanco}Eliminar ${rojo}ID${cierre}
${azul}[3]${cierre} ${rojo}>${cierre} ${blanco}Editar Expiracion ${verde}ID${cierre}
${azul}[4]${cierre} ${rojo}>${cierre} ${blanco}Lista de ${verde}ID${cierre}
${azul}[5]${cierre} ${rojo}>${cierre} ${blanco}Eliminar ${verde}ID ${blanco}Expirados${cierre}
${azul}[6]${cierre} ${rojo}>${cierre} ${blanco}Informacion de Clientes${cierre}
${azul}[7]${cierre} ${rojo}>${cierre} ${blanco}Token ${verdeR}Activos${cierre}
${azul}[8]${cierre} ${rojo}>${cierre} ${blanco}Instalar Panel Ultra Avanzado${cierre}
${azul}[0]${cierre} ${rojo}>${cierre} ${rojo}SALIR${cierre}
${bar2}"
read -p "$(echo -e "${blanco}seleccione [0-8]:${cierre}")" selection
case "$selection" in
	1)crear ;;
	2)eliminar ;;
  3)editar ;;
  4)lista ;;
  5)expirados ;;
  6)informacion_clientes;;
  7)online;;
  8)instalar_panel_nextjs ;;
	0)cd $HOME && exit 0;;
	*)
	echo -e "${rojo} Porfavor seleccione del [0-8]${cierre}"
	;;
esac
}
if [ -f $file_pass ]; then
	    echo
	    else
    define
fi
msg
menu
