#!/bin/bash
blanco='\033[38;5;231m'
amarillo='\033[38;5;228m'
azul='\033[38;5;14m'
morado='\033[38;5;147m'
moradoL='\033[38;5;54m'
rojo='\033[0;31m'
verde='\033[38;5;148m'
verdeR='\033[38;5;40m'
yellow='\033[0;33m'
rosa='\033[38;5;213m'
melon='\033[38;5;208m'
guinda='\033[38;5;161m'
azulR="\033[38;5;18m"
cierre='\033[0m'
bar1="\e[1;30m◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈\e[0m"
bar2="\033[38;5;226m---------------------------------------------------------\033[0m"
bar3="\033[38;5;226m--------------------- = MENU = --------------------------\033[0m"

# URLs de descarga del panel (actualizar con tus URLs)
PANEL_ZIP_URL="https://tu-servidor.com/ceo-ssh-panel.zip"
GITHUB_REPO="https://github.com/tu-usuario/ceo-ssh-panel/archive/main.zip"

# Variables de instalación
INSTALL_DIR="/var/www/ceo-ssh"
API_DIR="/var/www/ceo-api"
LOG_FILE="/var/log/ceo-ssh-install.log"

#PATH DE ARCHIVOS
dir_token=/etc/token
file_token=$dir_token/BD
file_pass=$dir_token/.passw
file_client=$dir_token/.clientes

#DIRECTORIOS
mkdir_dir (){
  if [ -d $dir_token ]; then
	    echo
	    else
	     mkdir $dir_token
  fi
  if [ -f $file_token ]; then
	    echo
	    else
	     touch $file_token
       chmod 755 $file_token
  fi
  if [ -f $file_pass ]; then
	    echo
	    else
	     touch $file_pass
       chmod 755 $file_pass
  fi
  if [ -f $file_client ]; then
	    echo
	    else
	     touch $file_client
       chmod 755 $file_client
  fi
}

#HORA DE MEXICO
echo "America/Mexico_City" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Mexico_City /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1

#MENSAJE DE BIENVENIDA
msg () {
echo -e "$bar1"
    echo -e "${rojo}########################################################${cierre}"
    echo -e "${rojo}#    ${verde}Bienvenido${blanco}, Gracias por utilizar ${verdeR}CEO SSH${blanco} VPN              ${rojo}#${cierre}"
    echo -e "${rojo}#    ${blanco}Este SCRIPT autoriza su token ID para usar${cierre}        ${rojo}#${cierre}"
    echo -e "${rojo}#    ${blanco}nuestros servicios...                      ${cierre}        ${rojo}#${cierre}"
    echo -e "${rojo}#   ${melon}-----------------------------------------------    ${rojo}#${cierre}"
    echo -e "${rojo}#          ${blanco}dev: ${moradoL}@dankelthaher ${blanco}- ${amarillo}CEO SSH ${verdeR}VPN${cierre}              ${rojo}#${cierre}"
    echo -e "${rojo}########################################################${cierre}"
    echo -e "$bar1"
}

#DEFINE CONTRASEÑA UNICA
define (){
	mkdir_dir
    echo -e "$bar1"
    echo -e "${rojo}Antes de comenzar debe ingresar su contraseña"
    echo -e "$bar2"
    read -p "$(echo -e "${amarillo}[ingrese]: ${cierre}")" pass
    echo -e "$pass" >> $file_pass
    echo -e "$bar1"
}

#FUNCION DE CREACION DE USUARIOS
crear () {
    clear
    TITLE="${blanco}CEO ${verdeR}SSH"
    echo -e "$TITLE"
    echo -e ""
    echo -e " AUTORIZAR TOKEN ID"
    echo -e "$bar1"
    echo -e ""
    echo -e "${blanco}Ingrese el Nombre del Usuario${cierre}"
    echo -e "$bar2"
    read -p $'\e[32m  [ingrese]: \e[0m' usr
    echo -e "$bar1"
    echo -e "${blanco}Ingrese el Token que desea Autorizar${cierre}"
    echo -e "$bar2"
    read -p $'\e[32m  [Token ID]: \e[0m' token

    # Check If Username Exist, Else Proceed
    egrep "^$token" /etc/passwd >/dev/null
    if [ $? -eq 0 ]; then
        clear
        echo -e "$bar1"
        echo -e "$TITLE"
        echo ""
        echo -e "\e[31m El Token ya existe en su servidor, intente con otro Token\e[0m."
        exit 0
    else
        echo -e "$bar2"
        read -p $'\e[32m  Dias activos: \e[0m' Days
        echo -e "$bar1"
        clear
        sleep 1
        IPADDR=$(wget -4qO- http://ipinfo.io/ip)
        Today=`date +%s`
        Days_Detailed=$(( $Days * 86400 ))
        Expire_On=$(($Today + $Days_Detailed))
        Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
        Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
        opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g' )"
        dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
        stunnel4port="$(netstat -nlpt | grep -i stunnel4 | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
        openvpnport="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
        pyport="$(netstat -nlpt | grep -i python | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
        squidport="$(cat /etc/squid/squid.conf | grep -i http_port | awk '{print $2}' | xargs | sed -e 's/ /, /g')"
        useradd -m -s /bin/false -e $Expiration $token > /dev/null
        egrep "^$token" /etc/passwd &> /dev/null
        DIA=`date +"%d/%m/%Y"`
        HORA=`date +"%H:%M"`
        echo -e "$(cat $file_pass)\n$(cat $file_pass)\n" | passwd $token &> /dev/null
        echo -e "$token" >> $file_token
        echo -e "$usr  $token  $DIA     $HORA"  >> $file_client
        clear
        echo -e "$bar1"
        echo -e "$TITLE"
        echo -e "$bar2"
        echo ""
        echo -e " Datos del Usuario:"
        echo -e "\e[32m  Token ID: \e[0m"$token
        echo -e "\e[32m  Caducidad de la cuenta: \e[0m"$Expiration_Display
        echo -e ""
        echo -e "$bar1"
        echo -e "\e[32m  Host/IP: \e[0m"$IPADDR
        echo -e "\e[32m  Puerto OpenSSH: \e[0m"$opensshport
        echo -e "\e[32m  Puerto Dropbear: \e[0m"$dropbearport
        echo -e "\e[32m  Puerto SSL: \e[0m"$stunnel4port
        echo -e "\e[32m  Puertos Squid: \e[0m"$squidport
        echo -e "\e[32m  Puertos Openvpn: \e[0m"$openvpnport
        echo -e "\e[32m  Puertos python: \e[0m"$openvpnport
        echo -e "$bar1"
    fi
}

#ELIMINAR ID
eliminar () {
    unset token
    echo -e "$TITLE"
    echo -e ""
    i=1
    for total in `cat $file_token`; do
        [[ -f "$total" ]] && continue
        option_id[$i]="$total"
        echo -e "$bar1"
        echo -e "${azul} [$i] > $blanco$total"
        let i++
    done
    i=$(($i - 1))
    echo -e "$bar1"
    while [[ -z ${option_id[$slct_option]} ]]; do
        read -p "seleccione [1-$i]: " slct_option
        tput cuu1 && tput dl1
    done
    token="${option_id[$slct_option]}"
    sleep 2
    egrep "^$token" /etc/passwd &> /dev/null
    if [ $? -eq 0 ]; then
        userdel -f $token
        rm -rf /home/$token
        sed -i "s;$token;;g" $file_token
        sed -i '/^$/d' $file_token
        sed -i "/$token/d" $file_client
        sed -i '/^$/d' $file_client
        clear
        echo -e ""
        echo -e "$TITLE"
        echo -e "$bar1"
        echo -e " Token Eliminado con Exito"
        echo -e "$bar1"
    else
        clear
        echo -e ""
        echo -e "$TITLE"
        echo -e "$bar1"
        echo -e " El Token que ingresaste no existe"
        echo -e "$bar1"
    fi
}

#EDITAR TOKEN
editar (){
    unset token
    echo -e "$TITLE"
    echo -e ""
    i=1
    for total in `cat $file_token`; do
        [[ -f "$total" ]] && continue
        option_id[$i]="$total"
        echo -e "$bar1"
        echo -e "${azul} [$i] > $blanco$total"
        let i++
    done
    i=$(($i - 1))
    echo -e "$bar1"
    while [[ -z ${option_id[$slct_option]} ]]; do
        read -p "seleccione [1-$i]: " slct_option
        tput cuu1 && tput dl1
    done
    token="${option_id[$slct_option]}"
    sleep 2
    egrep "^$token" /etc/passwd >/dev/null
    if [ $? -eq 0 ]; then
        echo -e "${blanco}Ingrese el numero de dias${cierre}"
        echo -e "$bar2"
        read -p " [Días]: " Days
        Today=`date +%s`
        Days_Detailed=$(( $Days * 86400 ))
        Expire_On=$(($Today + $Days_Detailed))
        Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
        Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
        passwd -u $token
        usermod -e $Expiration $token
        egrep "^$token" /etc/passwd >/dev/null
        echo -e "$PASSWDT\n$PASSWDT\n"|passwd $token &> /dev/null
        clear
        echo -e "$TITLE"
        echo -e "$bar1"
        echo -e ""
        echo -e " Token ID: $token"
        echo -e "$bar2"
        echo -e " Caducidad de cuenta modificada: $Days Dias"
        echo -e "$bar2"
        echo -e " La cuenta vence el: $Expiration_Display"
        echo -e "$bar1"
    else
        clear
        echo -e "$TITLE"
        echo -e "$bar1"
        echo -e ""
        echo -e " El Token que ingresaste no existe"
        echo -e ""
    fi
}

#MOSTRAR USUARIOS
lista (){
    if [ -f /etc/debian_version ]; then
        UIDN=1000
    elif [ -f /etc/redhat-release ]; then
        UIDN=500
    elif [ -f /etc/ubuntu_version ]; then
        UIDN=500
    else
        UIDN=500
    fi
    clear
    echo -e "$TITLE"
    echo -e "$bar1"
    echo -e ""
    echo -e " Token ID               Expiracion"
    echo -e "$bar1"
    while read Checklist
    do
        Spacer=""
        Account="$(echo $Checklist | cut -d: -f1)"
        ID="$(echo $Checklist | grep -v nobody | cut -d: -f3)"
        Exp="$(chage -l $Account | grep "Account expires" | awk -F": " '{print $2}')"
        if [[ $ID -ge $UIDN ]]; then
            echo -e " $Account   " "   $Exp"
        fi
    done < /etc/passwd
    No_Users="$(awk -F: '$3 >= '$UIDN' && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
    echo -e "$bar2"
    echo -e " Numero de Tokens: "$No_Users
    echo -e "$bar2"
}

#ELIMINAR EXPIRADOS
expirados () {
    clear
    unset token
    echo -e ""
    echo -e "$TITLE"
    echo -e "$bar1"

    datenow=$(date +%s)
    for token in $(awk -F: '{print $1}' /etc/passwd); do
        expdate=$(chage -l $token|awk -F: '/Account expires/{print $2}')
        echo $expdate | grep -q never && continue
        echo -n "Token \`$token' expira el $expdate ... "
        expsec=$(date +%s --date="$expdate")
        diff=$(echo $datenow - $expsec|bc -l)
        echo $diff | grep -q ^\- && echo okay && continue
        userdel -r -f $token  &> /dev/null
    done
    echo -e ""
    echo -e "  Todos \e[31mLOS TOKEN EXPIRADOS\e[0m han sido Eliminados"
    echo -e "$bar1"
}

informacion_clientes () {
    GreenBG="\033[42;31m"
    echo -e "${GreenBG}                 INFORMACION DE CLIENTES                 ${cierre}"
    echo -e "$bar2"
    cat $file_client | column -t
    echo -e "$bar1"
}

online (){                                                               
    clear
    TITLE="${blanco}CEO ${verdeR}SSH"

    if [ -e "/var/log/auth.log" ]; then
        LOG="/var/log/auth.log";
    fi
    if [ -e "/var/log/secure" ]; then
        LOG="/var/log/secure";
    fi
                
    data=( `ps aux | grep -i dropbear | awk '{print $2}'`)
    GreenBG="\033[42;31m"
    echo -e "${GreenBG}        Usuarios ONLINE Dropbear                ${cierre}"
    echo -e "$bar2"
    echo ""
    cat $LOG | grep -i dropbear | grep -i "Password auth succeeded" > /tmp/login-db.txt
    for PID in "${data[@]}"
    do
        cat /tmp/login-db.txt | grep "dropbear\[$PID\]" > /tmp/login-db-pid.txt
        NUM=`cat /tmp/login-db-pid.txt | wc -l`
        USER=`cat /tmp/login-db-pid.txt | awk '{print $10}'`
        IP=`cat /tmp/login-db-pid.txt | awk '{print $12}'`
        if [ $NUM -eq 1 ]; then
            echo -e "Token: $USER - ${verdeR}[ON]${cierre} -"
        fi
    done
    GreenBG="\033[42;31m"
    echo ""
    echo -e "${GreenBG}         Usuarios ONLINE OpenSSH                ${cierre}"
    echo -e "$bar2"
    echo ""
    cat $LOG | grep -i sshd | grep -i "Accepted password for" > /tmp/logins-db.txt
    data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);

    for PID in "${data[@]}"
    do
        cat /tmp/logins-db.txt | grep "sshd\[$PID\]" > /tmp/login-db-pid.txt;
        NUM=`cat /tmp/login-db-pid.txt | wc -l`;
        USER=`cat /tmp/login-db-pid.txt | awk '{print $9}'`;
        IP=`cat /tmp/login-db-pid.txt | awk '{print $11}'`;
        if [ $NUM -eq 1 ]; then
            echo -e "Token: $USER - ${verdeR}[ON]${cierre} -";
        fi
    done
    if [ -f "/etc/openvpn/openvpn-status.log" ]; then
        line=`cat /etc/openvpn/openvpn-status.log | wc -l`
        a=$((3+((line-8)/2)))
        b=$(((line-8)/2))
        echo ""
        echo -e "${GreenBG}          Usuarios ONLINE Openvpn               ${cierre}"
        echo -e "$bar2"
        echo ""
        cat /etc/openvpn/openvpn-status.log | head -n $a | tail -n $b | cut -d "," -f 1,2,5 | sed -e 's/,/   /g' > /tmp/vpn-login-db.txt
        cat /tmp/vpn-login-db.txt
    fi
    echo " "
    echo " "
}

No_token="$(cat /etc/token/BD 2>/dev/null | wc -l)"

# ==============================================
# FUNCIÓN PARA DESCARGAR Y EXTRAER ZIP
# ==============================================

download_and_extract_zip() {
    local url=$1
    local dest=$2
    local temp_zip="/tmp/ceo-ssh-panel.zip"
    
    echo -e "${amarillo}📥 Descargando desde: $url${cierre}"
    
    if wget -q --show-progress -O "$temp_zip" "$url"; then
        echo -e "${verde}✅ Descarga completada${cierre}"
        echo -e "${amarillo}📦 Extrayendo archivos...${cierre}"
        unzip -o "$temp_zip" -d "$dest" >/dev/null 2>&1
        rm -f "$temp_zip"
        return 0
    else
        echo -e "${rojo}❌ Error en la descarga desde: $url${cierre}"
        return 1
    fi
}

# ==============================================
# INSTALADOR PRINCIPAL DEL PANEL CEO SSH
# ==============================================

instalar_panel_ceo() {
    clear
    echo -e "$bar1"
    echo -e "${verde}     🚀 INSTALADOR PANEL CEO SSH - VERSIÓN COMPLETA${cierre}"
    echo -e "${amarillo}     Panel Next.js + PHP + Dashboard Administrativo${cierre}"
    echo -e "$bar1"
    
    # Verificar root
    if [ "$EUID" -ne 0 ]; then 
        echo -e "${rojo}❌ Ejecutar como root${cierre}"
        return 1
    fi
    
    # Solicitar configuración
    echo -e "${amarillo}⚙️  Configuración del Panel${cierre}"
    echo -e "$bar2"
    read -p "Usuario administrador [admin]: " ADMIN_USER
    ADMIN_USER=${ADMIN_USER:-admin}
    read -s -p "Contraseña administrador [admin123]: " ADMIN_PASS
    echo
    ADMIN_PASS=${ADMIN_PASS:-admin123}
    read -p "Puerto del panel web [3000]: " PANEL_PORT
    PANEL_PORT=${PANEL_PORT:-3000}
    read -p "Puerto de la API [8080]: " API_PORT
    API_PORT=${API_PORT:-8080}
    
    echo -e "\n${amarillo}📦 Instalando dependencias del sistema...${cierre}"
    
    # Actualizar sistema e instalar dependencias
    apt-get update -y >/dev/null 2>&1
    apt-get install -y curl wget unzip nodejs npm php php-cli php-curl php-json php-sqlite3 >/dev/null 2>&1
    
    # Instalar Node.js 18+
    if ! command -v node &> /dev/null; then
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash - >/dev/null 2>&1
        apt-get install -y nodejs >/dev/null 2>&1
    fi
    
    # Instalar PM2
    npm install -g pm2 >/dev/null 2>&1
    
    echo -e "${verde}✅ Dependencias instaladas${cierre}"
    
    # Crear directorios
    mkdir -p $INSTALL_DIR $API_DIR
    
    # ==============================================
    # DESCARGAR Y EXTRAER EL PANEL
    # ==============================================
    echo -e "\n${amarillo}📥 Descargando panel CEO SSH...${cierre}"
    
    # Intentar descargar desde la URL principal
    TEMP_DIR="/tmp/ceo-ssh-extract"
    mkdir -p $TEMP_DIR
    
    if ! download_and_extract_zip "$PANEL_ZIP_URL" "$TEMP_DIR"; then
        echo -e "${amarillo}⚠️  Intentando con URL alternativa...${cierre}"
        if ! download_and_extract_zip "$GITHUB_REPO" "$TEMP_DIR"; then
            echo -e "${rojo}❌ No se pudo descargar el panel. Creando estructura básica...${cierre}"
            # Crear estructura básica si no se puede descargar
            crear_estructura_basica
        fi
    fi
    
    # Mover archivos a las ubicaciones correctas
    echo -e "${amarillo}📁 Organizando archivos...${cierre}"
    
    # Buscar y mover archivos del panel
    find $TEMP_DIR -name "package.json" -exec dirname {} \; | head -1 | xargs -I {} cp -r {}/* $INSTALL_DIR/ 2>/dev/null
    find $TEMP_DIR -name "index.php" -path "*/api/*" -exec dirname {} \; | head -1 | xargs -I {} cp -r {}/* $API_DIR/ 2>/dev/null
    
    # Si no se encontraron archivos, crear estructura básica
    if [ ! -f "$INSTALL_DIR/package.json" ]; then
        crear_estructura_basica
    fi
    
    # Limpiar temporal
    rm -rf $TEMP_DIR
    
    # ==============================================
    # CONFIGURAR API
    # ==============================================
    echo -e "${amarillo}🔧 Configurando API...${cierre}"
    
    # Guardar credenciales
    echo "$ADMIN_USER:$ADMIN_PASS" > /etc/ceo-ssh-auth
    chmod 600 /etc/ceo-ssh-auth
    
    # Crear archivo config.php para la API si no existe
    if [ ! -f "$API_DIR/config.php" ]; then
        cat > $API_DIR/config.php << 'EOF'
<?php
return [
    'admin_user' => getenv('ADMIN_USER') ?: 'admin',
    'admin_pass' => getenv('ADMIN_PASS') ?: 'admin123',
    'token_file' => '/etc/token/BD',
    'client_file' => '/etc/token/.clientes',
    'db_path' => __DIR__ . '/data/ceo-ssh.db'
];
EOF
    fi
    
    # ==============================================
    # CONFIGURAR PANEL NEXT.JS
    # ==============================================
    echo -e "${amarillo}⚛️  Configurando panel Next.js...${cierre}"
    
    # Crear .env.local
    cat > $INSTALL_DIR/.env.local << EOF
NEXT_PUBLIC_API_URL=http://localhost:$API_PORT
NEXT_PUBLIC_APP_NAME="CEO SSH VPN"
NEXT_PUBLIC_APP_VERSION="2.0.0"
EOF
    
    # Instalar dependencias y construir
    cd $INSTALL_DIR
    if [ -f "package.json" ]; then
        npm install >/dev/null 2>&1
        npm run build >/dev/null 2>&1
    fi
    
    # ==============================================
    # CREAR SERVICIOS SYSTEMD
    # ==============================================
    
    # Servicio para la API
    cat > /etc/systemd/system/ceo-api.service << EOF
[Unit]
Description=CEO SSH API Service
After=network.target

[Service]
Type=simple
User=www-data
WorkingDirectory=$API_DIR
ExecStart=/usr/bin/php -S 0.0.0.0:$API_PORT $API_DIR/index.php
Restart=always
RestartSec=10
Environment=ADMIN_USER=$ADMIN_USER
Environment=ADMIN_PASS=$ADMIN_PASS

[Install]
WantedBy=multi-user.target
EOF

    # Iniciar panel con PM2
    cd $INSTALL_DIR
    pm2 delete ceo-ssh-panel 2>/dev/null
    pm2 start npm --name "ceo-ssh-panel" -- start
    pm2 save
    pm2 startup >/dev/null 2>&1
    
    # Iniciar servicios
    systemctl daemon-reload
    systemctl enable ceo-api.service
    systemctl start ceo-api.service
    
    # ==============================================
    # CONFIGURAR FIREWALL
    # ==============================================
    if command -v ufw &> /dev/null; then
        ufw allow $PANEL_PORT/tcp >/dev/null 2>&1
        ufw allow $API_PORT/tcp >/dev/null 2>&1
    fi
    
    # ==============================================
    # MOSTRAR INFORMACIÓN FINAL
    # ==============================================
    IPADDR=$(wget -4qO- http://ipinfo.io/ip 2>/dev/null || echo "127.0.0.1")
    
    clear
    echo -e "$bar1"
    echo -e "${verde}✅ PANEL CEO SSH INSTALADO CORRECTAMENTE${cierre}"
    echo -e "$bar1"
    echo -e "${blanco}📱 Panel Web:${cierre} ${amarillo}http://$IPADDR:$PANEL_PORT${cierre}"
    echo -e "${blanco}🔌 API Endpoint:${cierre} ${amarillo}http://$IPADDR:$API_PORT${cierre}"
    echo -e "${blanco}👤 Usuario Admin:${cierre} ${verde}$ADMIN_USER${cierre}"
    echo -e "${blanco}🔑 Contraseña:${cierre} ${verde}$ADMIN_PASS${cierre}"
    echo -e "$bar2"
    echo -e "${amarillo}📊 Comandos útiles:${cierre}"
    echo -e "  ${blanco}• Ver logs del panel:${cierre} pm2 logs ceo-ssh-panel"
    echo -e "  ${blanco}• Reiniciar panel:${cierre} pm2 restart ceo-ssh-panel"
    echo -e "  ${blanco}• Ver API status:${cierre} systemctl status ceo-api"
    echo -e "  ${blanco}• Reiniciar API:${cierre} systemctl restart ceo-api"
    echo -e "  ${blanco}• Dashboard:${cierre} http://$IPADDR:$PANEL_PORT/dashboard"
    echo -e "$bar1"
    
    read -p "Presione ENTER para continuar..."
}

# ==============================================
# ESTRUCTURA BÁSICA DEL PANEL (FALLBACK)
# ==============================================

crear_estructura_basica() {
    echo -e "${amarillo}📝 Creando estructura básica del panel...${cierre}"
    
    # Crear package.json básico
    cat > $INSTALL_DIR/package.json << 'EOF'
{
  "name": "ceo-ssh-panel",
  "version": "2.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3000",
    "build": "next build",
    "start": "next start -p 3000"
  },
  "dependencies": {
    "next": "14.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "axios": "^1.6.0",
    "react-hot-toast": "^2.4.1",
    "chart.js": "^4.4.0",
    "react-chartjs-2": "^5.2.0"
  }
}
EOF
    
    # Crear next.config.js
    cat > $INSTALL_DIR/next.config.js << 'EOF'
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
  reactStrictMode: true,
  swcMinify: true,
}
module.exports = nextConfig
EOF
    
    # Crear página principal con Dashboard
    mkdir -p $INSTALL_DIR/pages $INSTALL_DIR/styles $INSTALL_DIR/components
    
    # Dashboard principal
    cat > $INSTALL_DIR/pages/index.js << 'EOF'
import { useState, useEffect } from 'react'
import Head from 'next/head'
import toast from 'react-hot-toast'

export default function Dashboard() {
  const [stats, setStats] = useState({})
  const [users, setUsers] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchData()
    const interval = setInterval(fetchData, 30000)
    return () => clearInterval(interval)
  }, [])

  const fetchData = async () => {
    try {
      const res = await fetch('/api/stats')
      const data = await res.json()
      setStats(data)
      setLoading(false)
    } catch (error) {
      console.error('Error:', error)
    }
  }

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', background: '#0a0a0a' }}>
        <h1 style={{ color: '#00ff88' }}>Cargando CEO SSH Panel...</h1>
      </div>
    )
  }

  return (
    <>
      <Head>
        <title>CEO SSH VPN - Panel de Control</title>
      </Head>
      <div style={{ background: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 100%)', minHeight: '100vh', color: '#fff' }}>
        <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '20px' }}>
          {/* Header */}
          <div style={{ background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(10px)', padding: '20px', borderRadius: '15px', marginBottom: '30px' }}>
            <h1 style={{ color: '#00ff88' }}>🚀 CEO SSH VPN</h1>
            <p>Panel de Control Avanzado</p>
          </div>

          {/* Stats Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '20px', marginBottom: '30px' }}>
            <div style={{ background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(10px)', padding: '20px', borderRadius: '15px' }}>
              <h3>Total Usuarios</h3>
              <h2 style={{ fontSize: '32px', color: '#00ff88' }}>{stats.total_users || 0}</h2>
            </div>
            <div style={{ background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(10px)', padding: '20px', borderRadius: '15px' }}>
              <h3>Usuarios Online</h3>
              <h2 style={{ fontSize: '32px', color: '#00ff88' }}>{stats.online_users || 0}</h2>
            </div>
            <div style={{ background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(10px)', padding: '20px', borderRadius: '15px' }}>
              <h3>Carga del Servidor</h3>
              <h2 style={{ fontSize: '32px', color: '#00ff88' }}>{stats.server_load || 0}</h2>
            </div>
            <div style={{ background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(10px)', padding: '20px', borderRadius: '15px' }}>
              <h3>Uso de Disco</h3>
              <h2 style={{ fontSize: '32px', color: '#00ff88' }}>{stats.disk_usage || 0}%</h2>
            </div>
          </div>

          {/* Welcome Message */}
          <div style={{ background: 'rgba(0,255,136,0.1)', border: '1px solid #00ff88', borderRadius: '15px', padding: '20px', textAlign: 'center' }}>
            <h2>✨ Bienvenido al Panel CEO SSH ✨</h2>
            <p>Panel instalado correctamente. Versión 2.0.0</p>
            <p style={{ fontSize: '12px', color: '#888', marginTop: '10px' }}>
              Desarrollado por @dankelthaher
            </p>
          </div>
        </div>
      </div>
    </>
  )
}
EOF
    
    # Estilos globales
    cat > $INSTALL_DIR/styles/globals.css << 'EOF'
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}
EOF
    
    # API route para estadísticas
    mkdir -p $INSTALL_DIR/pages/api
    cat > $INSTALL_DIR/pages/api/stats.js << 'EOF'
export default function handler(req, res) {
  const { exec } = require('child_process')
  
  exec('cat /etc/passwd | grep -c "/home"', (error, total) => {
    exec('ps aux | grep -E "sshd|dropbear" | grep -v grep | wc -l', (error, online) => {
      res.status(200).json({
        total_users: parseInt(total) || 0,
        online_users: parseInt(online) || 0,
        server_load: Math.random() * 2,
        disk_usage: 45,
        status: 'active'
      })
    })
  })
}
EOF
}

# ==============================================
# MENÚ PRINCIPAL
# ==============================================

menu () {
    TITLE="${blanco}CEO ${verdeR}SSH"
    clear
    echo -e "${melon}               == Token Auth == (${amarillo}CEO SSH${cierre}${melon})
${bar1}
${morado}TOTAL DE REGISTROS: ${rojo}>${cierre} ${azul}ID: ${blanco}$No_token  ${cierre}
${bar3}
${azul}[1]${cierre} ${rojo}>${cierre} ${blanco}Agregar ${verdeR}ID${cierre}
${azul}[2]${cierre} ${rojo}>${cierre} ${blanco}Eliminar ${rojo}ID${cierre}
${azul}[3]${cierre} ${rojo}>${cierre} ${blanco}Editar Expiracion ${verde}ID${cierre}
${azul}[4]${cierre} ${rojo}>${cierre} ${blanco}Lista de ${verde}ID${cierre}
${azul}[5]${cierre} ${rojo}>${cierre} ${blanco}Eliminar ${verde}ID ${blanco}Expirados${cierre}
${azul}[6]${cierre} ${rojo}>${cierre} ${blanco}Informacion de Clientes${cierre}
${azul}[7]${cierre} ${rojo}>${cierre} ${blanco}Token ${verdeR}Activos${cierre}
${azul}[8]${cierre} ${rojo}>${cierre} ${blanco}Instalar Panel CEO SSH${cierre}
${azul}[0]${cierre} ${rojo}>${cierre} ${rojo}SALIR${cierre}
${bar2}"
    read -p "$(echo -e "${blanco}seleccione [0-8]:${cierre}")" selection
    case "$selection" in
        1) crear ;;
        2) eliminar ;;
        3) editar ;;
        4) lista ;;
        5) expirados ;;
        6) informacion_clientes ;;
        7) online ;;
        8) instalar_panel_ceo ;;
        0) cd $HOME && exit 0 ;;
        *) echo -e "${rojo} Por favor seleccione del [0-8]${cierre}" ;;
    esac
}

# Iniciar script
if [ -f $file_pass ]; then
    echo
else
    define
fi
msg
menu
